steps:
  # Step 1: Upgrade npm to the latest version inside the build environment
  - name: node:20
    entrypoint: npm
    args: ["install", "-g", "npm@latest"]

  # Step 2: Run the Buildpacks build with pack
  - name: gcr.io/k8s-skaffold/pack
    args:
      - build
      - northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/cafe-api/cafe-api
      - --builder=gcr.io/buildpacks/builder:v1
      - --path=.
      - --trust-builder

images:
  - northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/cafe-api/cafe-api

logsBucket: gs://cafe-api-build-logs-f5ecfab1-f238-4ec6-a26xx

options:
  logging: LEGACY
