steps:
  # Step 1: Upgrade npm to the latest version inside the build environment
  - name: node:20
    entrypoint: npm
    args: ["install", "-g", "npm@latest"]

  # Step 2: Run the Buildpacks build with pack
  - name: gcr.io/k8s-skaffold/pack
    args:
      - build
      - gcr.io/$PROJECT_ID/cafe-api
      - --builder=gcr.io/buildpacks/builder:v1
      - --path=.
      - --trust-builder

images:
  - gcr.io/$PROJECT_ID/cafe-api

# Logs bucket must be top-level, not inside options
logsBucket: gs://cafe-api-build-logs-f5ecfab1-f238-4ec6-a26xx

options:
  # LEGACY sends logs to both Cloud Logging and the bucket
  logging: LEGACY
