steps:
  - name: gcr.io/k8s-skaffold/pack
    args:
      - build
      - gcr.io/$PROJECT_ID/cafe-api
      - --builder=gcr.io/buildpacks/builder
      - --path=.
images:
  - gcr.io/$PROJECT_ID/cafe-api
