steps:
  - name: gcr.io/buildpacks/builder:latest
    args:
      - .
    env:
      - GOOGLE_BUILDABLE=gcr.io/$PROJECT_ID/cafe-api

images:
  - gcr.io/$PROJECT_ID/cafe-api

options:
  logging: CLOUD_LOGGING_ONLY

